title: Storm Spirit
email: wwulfric@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  这是我的中文博客，记录自己在技术、生活等方面的一些感想。博客叫 Storm Spirit，
  因为我特别喜欢 Dota 里蓝猫这个英雄，可惜玩得不好……
  希望自己能够通过博客，得到成长。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wwulfric.github.io" # the base hostname & protocol for your site
github_username:  wwulfric

# Build settings
# KramdownPygments is based on kramdown and share config
markdown: KramdownPygments
kramdown:
  input: GFM
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "wulfric"
      comments: true
      analytics: true
analytics:
  provider: google
  google:
    tracking_id: 'UA-54608037-1'

comments:
  provider: "disqus"
  disqus:
    short_name: "storm-spirit"
sass:
  style: :compressed
