name: Build and Deploy Jekyll to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
    - source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout source
      uses: actions/checkout@v4
      with:
        ref: 'source'  # 确保从 source 分支检出代码

    - name: Checkout articles
      uses: actions/checkout@v4
      with:
        repository: wwulfric/articles
        # token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: ${{ github.workspace }}/_posts  # 下载到这个目录

    - name: mv articles/images to sources
      run: |
        mv ${{ github.workspace }}/_posts/images/* ${{ github.workspace }}/images/
        sed -i 's#(images\/#(\/images\/#g' ${{ github.workspace }}/_posts/*.md
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.6'
        bundler-cache: true
    - name: Build jekyll
      run: bundle exec jekyll build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: master  # 将生成的页面推送到 master 分支
        keep_files: true  # 保留 master 分支中现有的文件on:
